global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "gestion_utilisateur"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.208.1:8081"]
        labels:
          application: "Gestion Utilisateur Application"


